name: PDGHPIN
main: me.mchiappinam.pdghpin.Main
version: 1.0
depends: [AuthMe,xAuth,PDGHAuth]
website: http://pdgh.com.br/
commands:
   pin:
      description: Comando do PIN.
      usage: /<command>
   apin:
      description: Comando de admin do PIN.
      usage: /<command>
